version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: find-me-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
