export enum TimeSlotEnum {
  MORNING_1 = 'MORNING_1',
  MORNING_2 = 'MORNING_2',
  MORNING_3 = 'MORNING_3',
  AFTERNOON_1 = 'AFTERNOON_1',
  AFTERNOON_2 = 'AFTERNOON_2',
  EVENING_1 = 'EVENING_1',
  EVENING_2 = 'EVENING_2',
  EVENING_3 = 'EVENING_3',
  EVENING_1_2 = 'EVENING_1_2',
}

export enum DayPatternEnum {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  MONDAY_WEDNESDAY = 'MONDAY_WEDNESDAY',
  TUESDAY_THURSDAY = 'TUESDAY_THURSDAY',
  MONDAY_WEDNESDAY_FRIDAY = 'MONDAY_WEDNESDAY_FRIDAY',
}
