services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
