name: Ci - Int E2E Tests

on: [ pull_request, pull_request_review ]

jobs:
  run-int-e2e-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api

    env:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/api?schema=public"
      APP_PORT: 3000
      NODE_ENV: test
      JWT_SECRET: test
      JWT_EXPIRES_IN: 3600000

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma
        run: npm run prisma:generate

      - name: Run int tests
        run: npm run test:int

      - name: Run e2e tests
        run: npm run test:e2e
